name: Test Set Version Job with Flask Project

on:
  workflow_dispatch:

jobs:
  set-version:
    permissions:
      contents: write
    uses: DanielPahima/templates/.github/workflows/version.yml@main

  lint:
    uses: DanielPahima/templates/.github/workflows/python-lint.yml@main