name: Test Set Version Job with Flask Project

on:
  push:
    branches:
      - '**' 

jobs:
  set-version:
    needs: [lint, unit-test]
    permissions:
      contents: write
    uses: DanielPahima/templates/.github/workflows/version.yml@main

  lint:
    uses: DanielPahima/templates/.github/workflows/python-lint.yml@main

  unit-test:
    permissions:
      contents: read
      checks: write 
    uses: DanielPahima/templates/.github/workflows/python-unit-tests.yml@main
  
  codeql:
    permissions:
      security-events: write
    uses: DanielPahima/templates/.github/workflows/security-test.yml@main
    with:
      languages: '["python"]' 
  