name: PR Pipeline 

on:
  pull_request: 
    branches:
      - 'dev'
      - 'main'

jobs:
  codeql:
    permissions:
      security-events: write
    uses: DanielPahima/templates/.github/workflows/security-test.yml@main
    with:
      languages: '["python"]' 
  


